### ISSUE TITLE
Link in description and online version not working

### ISSUE THREAD

**Issue by AndreasNasman** [vuesomedev/vue-3-playground#6]
Hi!

Thanks for this excellent playground repo!

I noticed the link in the **About** section, i.e. https://blacksonic.github.io/vue-3-playground/ isn't working.

The [online version on CodeSandbox](https://codesandbox.io/s/github/blacksonic/vue-3-playground) also doesn't seem to compile. I tried forking it but receive the same error.

```
$ vite
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/sandbox/node_modules/vite/dist/node/chunks/dep-efe32886.js:19:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

– Andreas

**Comment by sonicoder86** [comment]
Hi

thanks for noting, i've updated them.
Are they working now?

**Comment by AndreasNasman** [comment]
Both working now, thanks!
